GET http://localhost:4004/products/ProductsView?$filter=ID eq '4c4ccdac-0237-4e46-9b16-945c9546e036'

###
POST http://localhost:4004/products/Products
Content-Type: application/json

{   "name":"Bolo",
    "description": "Uma descrição para o produto",
    "price": 19.20,
    "stock": 100,
    "expirationDate": "2026-12-31",
    "imagemUrl": "http://example.com/image.jpg",
    "rating": 4.5
}

###
POST http://localhost:4004/products/Products(5bb30c29-127f-4fd2-bfdb-fb1849d83a20)/updateStock
Content-Type: application/json

{
    "quantityChange": 20,
    "operation": "ADD"
}