GET http://localhost:4004/products/Products?$filter=ID eq '6a93516e-afff-4b77-86ff-091579d2f303'

###
POST http://localhost:4004/products/Products
Content-Type: application/json

{   "name":"",
    "description": "Uma descrição para o produto",
    "price": 19.20,
    "stock": 100,
    "expirationDate": "2026-12-31",
    "imagemUrl": "http://example.com/image.jpg",
    "rating": 4.5
}

###
POST http://localhost:4004/products/Products(6a93516e-afff-4b77-86ff-091579d2f303)/updateStock
Content-Type: application/json

{
    "quantityChange": 20,
    "operation": "ADD"
}